const CASE_SAVE_KEY='courtroom-battle-progress-v2';
const rankOrder={D:1,C:2,B:3,A:4,S:5};
const campaignCases=[
 {id:1,no:'CASE 01',file:'案件卷宗 07',court:'臺北地方法院 · 第三法庭',title:'消失的十五分鐘',subtitle:'星河藝廊竊盜案',summary:'名畫失竊後，所有線索都指向一名前保全。你必須重建 21:15 至 21:30 的時間線。',defendant:'林哲宇',role:'藝廊前保全員',charge:'加重竊盜',sentence:'檢方求刑五年',mission:'找出時間線矛盾',asset:'assets/case-1-characters.png',start:'opening',phases:6,phaseNames:['','開庭陳述','目擊證人','館長證詞','物證攻防','最終反證','結案陳詞'],prosecutor:'沈若晴',defense:'陳奕衡',clueMax:5,requiredClues:['parking','access','frame','system'],initialEvidence:3},
 {id:2,no:'CASE 02',file:'案件卷宗 12',court:'新北地方法院 · 第二法庭',title:'無菌室的毒藥',subtitle:'中心醫院藥物調包案',summary:'手術病患因錯誤藥物命危，值班住院醫師成為唯一嫌疑人。但門禁與手術監測資料說著不同的故事。',defendant:'江柏辰',role:'外科住院醫師',charge:'業務過失重傷',sentence:'檢方求刑三年',mission:'破解藥品流向與門禁紀錄',asset:'assets/case-2-characters.png',start:'c2_open',phases:5,phaseNames:['','開庭陳述','藥局證詞','數位紀錄','藥品鑑定','結案陳詞'],prosecutor:'顧承岳',defense:'葉書妍',clueMax:4,requiredClues:['alibi','chain','identity'],initialEvidence:3},
 {id:3,no:'CASE 03',file:'案件卷宗 21',court:'智慧財產及商業法院',title:'凌晨兩點的登入者',subtitle:'天穹科技資料洩漏案',summary:'新產品原始碼在凌晨外洩，系統紀錄顯示工程師帳號登入。你必須證明帳號紀錄不等於本人操作。',defendant:'許安晴',role:'資深軟體工程師',charge:'營業秘密竊取',sentence:'求刑四年並求償',mission:'追查登入、裝置與伺服器日誌',asset:'assets/case-3-characters.png',start:'c3_open',phases:5,phaseNames:['','開庭陳述','登入證詞','裝置鑑識','伺服器追蹤','結案陳詞'],prosecutor:'唐紫寧',defense:'韓睿哲',clueMax:4,requiredClues:['device','chain','identity'],initialEvidence:3}
];
const caseRecords={
  1:{evidence:[...evidence],people:[...people],timeline:[...baseTimeline]},
  2:{evidence:[
    {id:'medorder',code:'A',name:'電子醫囑',desc:'22:31 醫囑指定止血藥 A，並非病患最後收到的藥物。',open:true},
    {id:'orvideo',code:'B',name:'手術室監測紀錄',desc:'被告 22:38 至 23:05 持續出現在手術室生命監測影像。',open:true},
    {id:'badge2',code:'C',name:'藥局門禁紀錄',desc:'被告名下的備用識別卡於 22:41 開啟無菌藥庫。',open:true},
    {id:'batch',code:'D',name:'批號鑑定',desc:'錯誤藥品來自藥局主任管理的召回批次。',open:false},
    {id:'override',code:'E',name:'權限異動紀錄',desc:'22:29 藥局主任重新啟用被告早已遺失的備用卡。',open:false}
  ],people:[{name:'江柏辰',role:'被告／外科住院醫師',desc:'案發時正在手術室協助急診手術。'},{name:'蘇曼君',role:'證人／藥局主任',desc:'聲稱被告親自進入無菌藥庫領藥。'},{name:'葉書妍',role:'辯護律師',desc:'擅長醫療資料與時間線攻防。'},{name:'顧承岳',role:'檢察官',desc:'主張帳號與門禁紀錄足以證明犯行。'}],timeline:[['22:29','備用識別卡被重新啟用'],['22:31','醫師開立止血藥 A'],['22:38','被告進入手術室'],['22:41','備用卡開啟藥庫'],['22:47','錯誤藥物送達手術室'],['23:05','手術監測影像結束']]},
  3:{evidence:[
    {id:'login',code:'A',name:'帳號登入紀錄',desc:'02:14 被告帳號自公司 VPN 登入原始碼系統。',open:true},
    {id:'phone',code:'B',name:'手機定位紀錄',desc:'被告手機整晚位於距公司二十公里的住處。',open:true},
    {id:'device',code:'C',name:'裝置指紋報告',desc:'登入裝置使用 Linux；被告公司電腦為 macOS。',open:true},
    {id:'token',code:'D',name:'權杖複製紀錄',desc:'管理員於前一日晚間匯出被告的登入權杖。',open:false},
    {id:'server',code:'E',name:'備份伺服器日誌',desc:'外洩檔案先由 CEO 管理帳號打包，再透過被告權杖下載。',open:false}
  ],people:[{name:'許安晴',role:'被告／資深工程師',desc:'負責核心演算法，但否認凌晨登入公司系統。'},{name:'沈維德',role:'證人／天穹科技執行長',desc:'主張只有被告有能力取得外洩資料。'},{name:'韓睿哲',role:'辯護律師',desc:'擅長數位鑑識與系統紀錄推理。'},{name:'唐紫寧',role:'檢察官',desc:'以帳號紀錄與存取權限建立指控。'}],timeline:[['前日 20:46','管理員匯出登入權杖'],['02:10','CEO 管理帳號打包原始碼'],['02:14','被告帳號透過 Linux 裝置登入'],['02:17','壓縮檔遭下載'],['08:30','公司通報資料外洩']]}
};

Object.assign(nodes,{
 c2_open:{phase:1,role:'審判長',speaker:'許正義',portrait:'法',text:'被告的備用卡在 22:41 進入藥庫，錯誤藥物隨後送入手術室。辯方主張為何？',choices:[['先確認被告當時的位置。','c2_where',5,'你把爭點放在客觀時間線。'],['備用卡一定是系統故障。','c2_fault',-3,'沒有資料支持系統故障。'],['醫療事故本來就難免。','c2_careless',-5,'這等同忽略病患受到的傷害。']]},
 c2_witness:{phase:2,role:'檢方證人',speaker:'蘇曼君',portrait:'證',text:'我看到江醫師在藥庫門口。他用自己的卡進去，還催促我不要多問。',choices:[['詢問她看到臉還是只看到白袍背影。','c2_sight',4,'證人承認只看見背影與識別卡。'],['直接說她才是調包者。','c2_attack',-5,'缺乏基礎的指控遭法官制止。'],['提出手術室監測紀錄。','c2_or',7,'客觀影像證明被告當時在手術室。']]},
 c2_log:{phase:3,role:'檢察官',speaker:'顧承岳',portrait:'檢',text:'即使人在手術室，被告也可能把卡交給共犯。卡片仍然屬於他。',choices:[['要求調查備用卡何時被啟用。','c2_unlock',7,'你取得權限異動紀錄。'],['承認可能有共犯。','c2_concede',-5,'你替檢方補上了缺少的故事。'],['只強調被告人很好。','c2_character',-3,'品格不能推翻數位紀錄。']]},
 c2_batch:{phase:4,role:'書記官',speaker:'鑑定結果',portrait:'證',text:'紀錄顯示蘇主任在 22:29 重新啟用備用卡；錯誤藥物也來自她負責封存的召回批次。',choices:[['結合權限與批號，指出主任控制整條藥物流向。','c2_connect',8,'兩份獨立紀錄形成一致證據鏈。'],['認為這只是行政疏失。','c2_admin',-3,'無法解釋刻意重啟他人卡片。'],['只要求醫院道歉。','c2_apology',-2,'這沒有處理被告是否犯罪。']]},
 c2_close:{phase:5,role:'審判長',speaker:'許正義',portrait:'法',text:'請辯方進行結案陳詞。',choices:[['門禁只證明卡片，不證明持卡者；影像與權限紀錄排除被告。','c2_win',8,'你清楚區分身分憑證與實際行為人。'],['醫師工作辛苦，請從輕量刑。','c2_lose',-5,'這近似承認犯罪。'],['醫院每個人都可能犯錯。','c2_vague',-3,'過度空泛，未建立合理懷疑。']]},
 c3_open:{phase:1,role:'審判長',speaker:'許正義',portrait:'法',text:'檢方提出被告帳號的登入紀錄。辯方要先挑戰哪一點？',choices:[['帳號登入是否等於本人操作。','c3_identity',6,'你抓住數位案件的身分認定問題。'],['公司產品其實不值錢。','c3_value',-4,'資料價值與登入者身分無關。'],['所有電腦紀錄都能造假。','c3_allfake',-4,'過度籠統的質疑沒有說服力。']]},
 c3_witness:{phase:2,role:'檢方證人',speaker:'沈維德',portrait:'證',text:'許安晴是唯一熟悉核心程式的人。凌晨登入的帳號也是她的，還能有誰？',choices:[['提出裝置指紋差異。','c3_device',7,'登入裝置的作業系統與被告電腦不同。'],['詢問公司有多少工程師。','c3_staff',2,'多人具備技術能力，唯一性主張變弱。'],['指控 CEO 嫉妒被告。','c3_jealous',-5,'沒有證據支持私人動機。']]},
 c3_token:{phase:3,role:'檢察官',speaker:'唐紫寧',portrait:'檢',text:'作業系統不同，也可能是被告使用私人電腦。她的權杖仍是登入必要條件。',choices:[['要求檢查權杖匯出與管理紀錄。','c3_unlock',7,'新的稽核紀錄顯示管理員曾匯出權杖。'],['承認私人電腦的可能性。','c3_concede',-4,'你讓裝置矛盾失去力量。'],['改談被告的工作表現。','c3_work',-2,'績效無法確認凌晨的操作人。']]},
 c3_server:{phase:4,role:'書記官',speaker:'數位鑑識結果',portrait:'證',text:'備份日誌顯示，原始碼在被告登入前四分鐘，已由 CEO 管理帳號完成打包。',choices:[['串連打包時間、權杖匯出與裝置指紋。','c3_connect',8,'三份紀錄指向同一套冒用流程。'],['只依靠手機定位。','c3_phoneonly',1,'手機位置不能完全證明本人位置。'],['認為可能是駭客隨機入侵。','c3_hacker',-3,'現有紀錄更像內部權限遭利用。']]},
 c3_close:{phase:5,role:'審判長',speaker:'許正義',portrait:'法',text:'請提出最終結論。',choices:[['帳號是被冒用的工具，真正操作者掌握管理權限與檔案打包權。','c3_win',8,'你以技術紀錄完整區分帳號與本人。'],['被告在家，所以絕對無罪。','c3_weak',1,'定位只是間接證據，結論略嫌武斷。'],['科技公司內鬥很常見。','c3_vague',-4,'一般印象不能取代本案證據。']]}
});
Object.assign(actions,{
 c2_where:()=> 'c2_witness',c2_fault:()=> 'c2_witness',c2_careless:()=> 'c2_witness',c2_sight:()=>{clue('sight');return'c2_log'},c2_attack:()=> 'c2_log',c2_or:()=>{clue('alibi');return'c2_log'},c2_unlock:()=>{unlock('override');return'c2_batch'},c2_concede:()=> 'c2_batch',c2_character:()=> 'c2_batch',c2_connect:()=>{unlock('batch');clue('chain');return'c2_close'},c2_admin:()=> 'c2_close',c2_apology:()=> 'c2_close',c2_win:()=>{clue('identity');return'finish'},c2_lose:()=> 'finish',c2_vague:()=> 'finish',
 c3_identity:()=> 'c3_witness',c3_value:()=> 'c3_witness',c3_allfake:()=> 'c3_witness',c3_device:()=>{clue('device');return'c3_token'},c3_staff:()=> 'c3_token',c3_jealous:()=> 'c3_token',c3_unlock:()=>{unlock('token');return'c3_server'},c3_concede:()=> 'c3_server',c3_work:()=> 'c3_server',c3_connect:()=>{unlock('server');clue('chain');return'c3_close'},c3_phoneonly:()=> 'c3_close',c3_hacker:()=> 'c3_close',c3_win:()=>{clue('identity');return'finish'},c3_weak:()=> 'finish',c3_vague:()=> 'finish'
});

let activeCase=campaignCases[0];
let saveData=loadProgress();
function loadProgress(){try{return JSON.parse(localStorage.getItem(CASE_SAVE_KEY))||{unlocked:3,results:{}}}catch{return{unlocked:3,results:{}}}}
function writeProgress(){localStorage.setItem(CASE_SAVE_KEY,JSON.stringify(saveData))}
function renderCaseSelect(){const cleared=Object.keys(saveData.results).filter(k=>saveData.results[k].won).length;$('totalProgress').style.width=(cleared/3*100)+'%';$('progressText').textContent=`${cleared} / 3 通關`;$('caseGrid').innerHTML=campaignCases.map(c=>{const res=saveData.results[c.id];return `<article class="case-card"><div class="case-art" style="background-image:url('${c.asset}')"></div><div class="case-card-content"><span class="case-no">${c.no}</span><h2>${c.title}</h2><p>${c.summary}</p><div class="case-meta"><span>${c.subtitle}</span><span class="case-rank">${res?res.rank:'—'}</span></div><button data-case="${c.id}">${res?'重新審理':'開啟卷宗'}</button></div></article>`}).join('');document.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>openCase(+b.dataset.case))}
function openCase(id){activeCase=campaignCases.find(c=>c.id===id);const rec=caseRecords[id];evidence.splice(0,evidence.length,...rec.evidence.map(x=>({...x})));people.splice(0,people.length,...rec.people);baseTimeline.splice(0,baseTimeline.length,...rec.timeline);$('briefCourt').textContent=activeCase.court;$('briefCaseNo').textContent=activeCase.file;$('briefTitle').textContent=activeCase.subtitle;$('briefSummary').textContent=activeCase.summary;$('briefDefendant').textContent=activeCase.defendant;$('briefDefendantRole').textContent=activeCase.role;$('briefCharge').textContent=activeCase.charge;$('briefSentence').textContent=activeCase.sentence;$('briefMission').textContent=activeCase.mission;$('briefHero').style.backgroundImage=`url('${activeCase.asset}')`;$('briefEvidence').innerHTML=evidence.slice(0,3).map(e=>`<div class="mini-evidence"><b>${e.code}</b><span>${e.name}<small>${e.desc}</small></span></div>`).join('');show('briefingScreen')}
function applyPortraits(){const url=`url('${activeCase.asset}')`;[['defensePortrait',0],['prosecutorPortrait',1]].forEach(([id,pos])=>{$(id).style.backgroundImage=url;$(id).className=`portrait character-portrait portrait-pos-${pos}`});$('defenseName').textContent=activeCase.defense;$('prosecutorName').textContent=activeCase.prosecutor;const speaker=$('dialogueSpeaker').textContent;let pos=speaker===activeCase.prosecutor?1:speaker===activeCase.defense||speaker==='你'?0:2;if(speaker.includes('主任')||speaker.includes('維德'))pos=3;$('speakerPortrait').style.backgroundImage=url;$('speakerPortrait').className=`portrait witness character-portrait portrait-pos-${pos}`}
const baseRenderNode=renderNode;
renderNode=function(id,feedback){baseRenderNode(id,feedback);$('phaseTotal').textContent=activeCase.phases;$('clueMax').textContent=activeCase.clueMax;$('phaseLabel').textContent=activeCase.phaseNames[state.phase]||'法庭攻防';applyPortraits()};
reset=function(){state={node:activeCase.start,jury:50,cred:5,clues:new Set(),phase:1,choices:0,mistakes:0,flags:{},history:[]};evidence.forEach((e,i)=>e.open=i<activeCase.initialEvidence);show('briefingScreen');renderDrawer('evidence')};
finish=function(){const missing=activeCase.requiredClues.filter(id=>!state.clues.has(id));const hasRequired=missing.length===0;const won=state.jury>=56&&hasRequired&&state.cred>0;const perfect=state.jury>=75&&hasRequired&&state.clues.size>=activeCase.clueMax-1&&state.cred>=3;show('verdictScreen');$('verdictTitle').textContent=won?'無罪':'有罪';$('verdictTitle').style.color=won?'#e3be72':'#ba5353';$('verdictSubtitle').textContent=won?`被告${activeCase.defendant}，罪名不成立`:`被告${activeCase.defendant}，罪名成立`;const score=state.jury+state.clues.size*9+state.cred*4-state.mistakes*3;const rank=perfect?'S':won&&score>=95?'A':won&&score>=75?'B':score>=55?'C':'D';$('rankValue').textContent=rank;$('scoreDetails').innerHTML=`<li>陪審團支持：${state.jury}%</li><li>關鍵矛盾：${state.clues.size} / ${activeCase.clueMax}</li><li>核心證據鏈：${hasRequired?'完整':'缺少 '+missing.length+' 項'}</li><li>法庭威信：${state.cred} / 5</li><li>錯誤攻防：${state.mistakes} 次</li>`;$('verdictReason').textContent=won?'你成功以客觀紀錄建立完整證據鏈，推翻檢方看似完整的指控。':hasRequired?'你的法庭表現未能說服陪審團。':'你漏掉了決定案件的核心矛盾；即使部分論點正確，仍不足以建立合理懷疑。';const old=saveData.results[activeCase.id];if(!old||rankOrder[rank]>rankOrder[old.rank])saveData.results[activeCase.id]={won,rank,score};writeProgress();buildCampaignAnalysis(won,rank)};
function buildCampaignAnalysis(won,rank){const lessons={1:'時間線、門禁與物證材質必須彼此一致。',2:'識別卡只能證明憑證被使用，不能直接證明持卡者本人。',3:'帳號紀錄、裝置指紋與管理權限必須分開判斷。'};$('analysisContent').innerHTML=`<p><b>${activeCase.subtitle}</b></p><p><b>本次結果：</b>${won?'無罪':'有罪'}，最高評價 ${rank}。</p><p><b>案件重點：</b>${lessons[activeCase.id]}</p><p><b>系統紀錄：</b>本次共做出 ${state.choices} 次選擇，發現 ${state.clues.size} 項關鍵矛盾，錯誤攻防 ${state.mistakes} 次。</p>`}

$('startBtn').onclick=()=>{renderCaseSelect();show('caseSelectScreen')};$('backToCasesBtn').onclick=()=>{renderCaseSelect();show('caseSelectScreen')};$('nextCaseBtn').onclick=()=>{renderCaseSelect();show('caseSelectScreen')};$('beginTrialBtn').onclick=()=>{state={node:activeCase.start,jury:50,cred:5,clues:new Set(),phase:1,choices:0,mistakes:0,flags:{},history:[]};show('gameScreen');renderNode(activeCase.start)};$('restartBtn').onclick=()=>openCase(activeCase.id);$('resetProgressBtn').onclick=()=>{if(confirm('確定要清除所有案件通關紀錄嗎？')){saveData={unlocked:3,results:{}};writeProgress();renderCaseSelect()}};
